### ISSUE TITLE
Your lock file does not contain a compatible set of packages. Please run composer update.

### ISSUE THREAD

**Issue by arantesk** [xbxstudios/free-product-dashboard#1]
![image](https://user-images.githubusercontent.com/85427336/235519735-90034b8b-8261-4bd7-84d1-f1d031553d17.png)

What version of PHP is recommend to use on this project?

**Comment by therealxbx** [comment]
I used `php 8.0` i think u can use `composer update` i think

**Comment by arantesk** [comment]
After the discord authentication this error shows
![image](https://user-images.githubusercontent.com/85427336/235524424-21ee14b2-17db-4a5d-958e-401817ceb043.png)

I suspected it was the php version, but nothing.

**Comment by arantesk** [comment]
Perfect, I think that last insert was missing in the bd.
Thanks!
